python -O start_train.py \
    --device cuda \
    --emb_dim_belief 128 \
    --emb_dim_private_belief 64 \
    --gamma_history 0.9 \
    --num_intention 5 \
    --hidden_dim_actor 512 \
    --hidden_dim_critic 512 \
    --hidden_dim_shared 512 \
    --hidden_dim_tom 256 \
    --hidden_dim_update 512 \
    --num_colors 4 \
    --num_ranks 5 \
    --num_players 2 \
    --hand_size 5 \
    --max_information_token 8 \
    --discount_factor 0.95 \
    --clip_epsilon 0.2 \
    --learning_rate_actor 1e-4 \
    --learning_rate_critic 3e-4 \
    --learning_rate_shared 3e-4 \
    --learning_rate_update 1e-3 \
    --learning_rate_tom 1e-3 \
    --num_training_epochs 4 \
    --max_training_timesteps 208896 \
    --max_episode_length 128 \
    --update_interval 4096 \
    --saving_interval 32 \
    --saving_dir checkpoints/Simplest-Private \
    --run_name Simplest-Private \
    --reward_type simplest \
    --alpha_tom_loss 0.1 \
    --num_parallel_games 32 \
    --deprecate_threshold 3

